export const projects = [
  {
    title: "AI Powered House Construction Cost Estimate App",
    description: "An intelligent agent for real-time construction material cost analysis and procurement optimization.",
    tags: ["Next.js", "Python", "OpenAI SDK"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fconstruction-material-cost-agent.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://construction-material-cost-agent.vercel.app/",
  },
  {
    title: "Meyuzas Design",
    description: "A premium fashion e-commerce platform featuring a custom headless CMS, secure Clerk authentication, and Payfast integration.",
    tags: ["Next.js", "Clerk", "Sanity", "Payfast"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fmeyuzasdesign.com&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://meyuzasdesign.com",
  },
  {
    title: "Angioplasty 3D Simulation",
    description: "Interactive 3D medical simulation of the angioplasty procedure for educational purposes.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fangioplasty.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://angioplasty.vercel.app",
  },
  {
    title: "Nike Clone - E-Commerce",
    description: "A high-fidelity clone of the Nike e-commerce platform, featuring product management with Sanity CMS and secure authentication via Clerk.",
    tags: ["Next.js", "Sanity", "Clerk", "Tailwind"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fhackathon3-temp3.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://hackathon3-temp3.vercel.app/",
  },
  {
    title: "AI Humanoid Robotics Assistant",
    description: "An intelligent interactive book and knowledge base for AI Humanoid Robotics, utilizing Qdrant vector search and OpenAI Agents for deep technical insights.",
    tags: ["Next.js", "Python", "PostgreSQL", "Qdrant", "OpenAI Agents"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fai-humanoid-robotics-7zcj.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://ai-humanoid-robotics-7zcj.vercel.app/",
  },
  {
    title: "AI-Powered Fullstack Todo App",
    description: "A sophisticated task management system featuring BetterAuth, an integrated AI chatbot, and MCP for enhanced task automation.",
    tags: ["Next.js", "BetterAuth", "Python", "OpenAI", "PostgreSQL", "MCP"],
    image: "https://api.microlink.io?url=https%3A%2F%2Ffullstack-todo-app-phase3.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://fullstack-todo-app-phase3.vercel.app/",
  },
  {
    title: "Compton Effect Simulation",
    description: "3D visualization of the Compton scattering effect, demonstrating X-ray photon interaction with matter.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fcompton-effect.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://compton-effect.vercel.app",
  },
  {
    title: "CRO Simulation",
    description: "A detailed 3D simulation of a Cathode Ray Oscilloscope (CRO) for physics laboratories.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fcro-delta.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://cro-delta.vercel.app",
  },
  {
    title: "Transformer Simulation",
    description: "Interactive 3D model exploring the working principles and components of electrical transformers.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Ftransformer-jade-one.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://transformer-jade-one.vercel.app",
  },
  {
    title: "Electrophoresis Simulation",
    description: "Digital laboratory simulation of the electrophoresis process for separating biological molecules.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Felectrophorisis.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://electrophorisis.vercel.app",
  },
  {
    title: "Newton's Ring Simulation",
    description: "Physics simulation demonstrating the optical interference pattern of Newton's rings.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fnewtons-ring.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://newtons-ring.vercel.app",
  },
  {
    title: "Gas Chromatography Simulation",
    description: "3D simulation of a gas chromatography lab setup, showing chemical separation processes.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fgas-chromatography.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://gas-chromatography.vercel.app",
  },
  {
    title: "Spectrophotometry Simulation",
    description: "Interactive 3D tool for understanding spectrophotometry and light absorption principles.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fspectrophotometry.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://spectrophotometry.vercel.app",
  },
  {
    title: "Micrometry Simulation",
    description: "Precise 3D simulation of microscopic measurement techniques using micrometers.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Fmicrometry.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://micrometry.vercel.app",
  },
  {
    title: "ECG Simulation",
    description: "3D medical visualization of heart electrical activity and electrocardiogram readings.",
    tags: ["HTML", "Three.js", "JavaScript"],
    image: "https://api.microlink.io?url=https%3A%2F%2Felectrocardiogram-psi.vercel.app&screenshot=true&meta=false&embed=screenshot.url",
    link: "https://electrocardiogram-psi.vercel.app",
  },
];
